backend:
  name: github
  repo: kdelalic/karlodelalic-astro
  branch: main
  base_url: https://karlodelalic.me
  auth_endpoint: /api/auth

media_folder: public/img
public_folder: /img

collections:
  - name: 'recipes'
    label: 'Recipe'
    folder: 'src/content/recipes'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', field: {label: 'Tag', name: 'tag', widget: 'string'} }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Notes', name: 'notes', widget: 'text', required: false } 
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'recipe' }
  - name: "custom-recipes"
    label: "Custom Recipe"
    folder: "src/content/custom-recipes"
    create: true
    slug: 'index'
    path: '{{title}}/index'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: 'Tags', name: 'tags', widget: 'list', field: {label: 'Tag', name: 'tag', widget: 'string'} }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Ingredients", name: "ingredients", widget: "list", field: { label: "Ingredient", name: "ingredient", widget: "string" } }
      - { label: "Body (Steps)", name: "body", widget: "markdown" }
      - { label: "Notes", name: "notes", widget: "markdown", required: false }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'custom-recipe' }
local_backend: true